### ISSUE TITLE
cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by ncde** [MSO4SC/MSOPortal#21] opened 2018-01-20 11:58 UTC
using the blueprint at http://www.csc.kth.se/~ncde/debug0.tar.gz
I create an instance and for every possible variable I use string as type 

the blueprint is simplified to isolate the error

the deployed instance gives the following problem: 

2018-01-20T11:52:36.417Z Starting 'install' workflow execution
2018-01-20T11:52:37.298Z Creating node main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:38.086Z Configuring node main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:38.820Z Starting node main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:39.351Z Sending task 'hpc_plugin.tasks.login_connection' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:39.577Z Task started 'hpc_plugin.tasks.login_connection' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:41.713Z Task succeeded 'hpc_plugin.tasks.login_connection' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:42.142Z Sending task 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:42.331Z Task started 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:45.262Z Task succeeded 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_node_tkj0so (main_hpc_node)
2018-01-20T11:52:47.243Z Creating node first_job_zdawgw (first_job)
2018-01-20T11:52:48.100Z Sending task 'hpc_plugin.tasks.preconfigure_job'
2018-01-20T11:52:48.291Z Task started 'hpc_plugin.tasks.preconfigure_job'
2018-01-20T11:52:48.100Z Sending task 'hpc_plugin.tasks.preconfigure_job'
2018-01-20T11:52:48.291Z Task started 'hpc_plugin.tasks.preconfigure_job'
2018-01-20T11:52:49.876Z Task succeeded 'hpc_plugin.tasks.preconfigure_job'
2018-01-20T11:52:50.070Z Configuring node first_job_zdawgw (first_job)
2018-01-20T11:52:51.293Z Starting node first_job_zdawgw (first_job)
2018-01-20T11:52:51.439Z Sending task 'hpc_plugin.tasks.bootstrap_job' first_job_zdawgw (first_job)
2018-01-20T11:52:51.582Z Task started 'hpc_plugin.tasks.bootstrap_job' first_job_zdawgw (first_job)
2018-01-20T11:52:54.005Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:53:09.156Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 1/60] first_job_zdawgw (first_job)
2018-01-20T11:53:09.300Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 1/60] first_job_zdawgw (first_job)
2018-01-20T11:53:11.460Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 1/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:53:26.627Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 2/60] first_job_zdawgw (first_job)
2018-01-20T11:53:26.768Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 2/60] first_job_zdawgw (first_job)
2018-01-20T11:53:29.027Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 2/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:53:44.122Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 3/60] first_job_zdawgw (first_job)
2018-01-20T11:53:44.267Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 3/60] first_job_zdawgw (first_job)
2018-01-20T11:53:46.505Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 3/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:54:01.598Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 4/60] first_job_zdawgw (first_job)
2018-01-20T11:54:01.759Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 4/60] first_job_zdawgw (first_job)
2018-01-20T11:54:04.202Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 4/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:54:19.270Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 5/60] first_job_zdawgw (first_job)
2018-01-20T11:54:19.363Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 5/60] first_job_zdawgw (first_job)
2018-01-20T11:54:21.712Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 5/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:54:36.880Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 6/60] first_job_zdawgw (first_job)
2018-01-20T11:54:37.074Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 6/60] first_job_zdawgw (first_job)
2018-01-20T11:54:39.558Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 6/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:54:54.636Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 7/60] first_job_zdawgw (first_job)
2018-01-20T11:54:54.774Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 7/60] first_job_zdawgw (first_job)
2018-01-20T11:54:57.324Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 7/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:55:12.459Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 8/60] first_job_zdawgw (first_job)
2018-01-20T11:55:12.565Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 8/60] first_job_zdawgw (first_job)
2018-01-20T11:55:14.728Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 8/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:55:29.890Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 9/60] first_job_zdawgw (first_job)
2018-01-20T11:55:30.023Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 9/60] first_job_zdawgw (first_job)
2018-01-20T11:55:32.274Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 9/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:55:47.442Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 10/60] first_job_zdawgw (first_job)
2018-01-20T11:55:47.575Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 10/60] first_job_zdawgw (first_job)
2018-01-20T11:55:49.846Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 10/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:56:04.932Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 11/60] first_job_zdawgw (first_job)
2018-01-20T11:56:05.051Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 11/60] first_job_zdawgw (first_job)
2018-01-20T11:56:07.308Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 11/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:56:22.450Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 12/60] first_job_zdawgw (first_job)
2018-01-20T11:56:22.450Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 12/60] first_job_zdawgw (first_job)
2018-01-20T11:56:22.552Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 12/60] first_job_zdawgw (first_job)
2018-01-20T11:56:24.816Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 12/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:56:39.970Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 13/60] first_job_zdawgw (first_job)
2018-01-20T11:56:40.165Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 13/60] first_job_zdawgw (first_job)
2018-01-20T11:56:42.583Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 13/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:56:57.753Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 14/60] first_job_zdawgw (first_job)
2018-01-20T11:56:57.884Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 14/60] first_job_zdawgw (first_job)
2018-01-20T11:57:00.331Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 14/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:57:15.511Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 15/60] first_job_zdawgw (first_job)
2018-01-20T11:57:15.653Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 15/60] first_job_zdawgw (first_job)
2018-01-20T11:57:17.909Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 15/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:57:32.976Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 16/60] first_job_zdawgw (first_job)
2018-01-20T11:57:33.102Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 16/60] first_job_zdawgw (first_job)
2018-01-20T11:57:36.356Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 16/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:57:51.541Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 17/60] first_job_zdawgw (first_job)
2018-01-20T11:57:51.717Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 17/60] first_job_zdawgw (first_job)
2018-01-20T11:57:53.951Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 17/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:58:09.118Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 18/60] first_job_zdawgw (first_job)
2018-01-20T11:58:09.262Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 18/60] first_job_zdawgw (first_job)
2018-01-20T11:58:12.317Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> cannot concatenate 'str' and 'int' objects [retry 18/60] first_job_zdawgw (first_job)
TypeError: cannot concatenate 'str' and 'int' objects
	Traceback (most recent call last):
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 635, in main
  File "/tmp/pip-build-98XWh3/cloudify-plugins-common/cloudify/dispatch.py", line 391, in handle
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 183, in bootstrap_job
    avoid)
  File "/opt/mgmtworker/env/plugins/default_tenant/debug0_t1x1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 253, in deploy_job
    call += ' ' + dinput
TypeError: cannot concatenate 'str' and 'int' objects

2018-01-20T11:58:27.468Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 19/60] first_job_zdawgw (first_job)
2018-01-20T11:58:27.578Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 19/60] first_job_zdawgw (first_job)

**Comment by ncde** [comment] 2018-01-20 15:19
it seems 
I can't use {get_input: hpc_directory}
as an argument to a bootstrap script 

I will implement a workaround on that

**Comment by gdolle** [comment] 2018-01-21 15:26
Can you check in your `local-blueprint.yaml` or in the portal form that you well put the quotes `""` around values ?

**Comment by VedatDurmaz** [comment] 2018-01-21 18:43
yes, i had to define integer variables in the blueprint inputs using nested quoted strings such as
```
    za_charge:
        description: ZA formal ligand charge
        default: "'0'"
        type: string
```
as soon as i wanted to use them as `{get_input: za_charge}` in the inputs list of a particular job's bootstrapping ...

**Comment by emepetres** [comment] 2018-01-22 14:15
This is duplicate of #17

**Closed by emepetres** 2018-01-22 14:15 UTC
Labels: duplicate
