### ISSUE TITLE
MarketPlace Offering should be provided by Organization 

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#91] opened 2018-06-07 19:49 UTC
Currently, MarkertPlace Offerings are provided by a developer but the offering is actually usually not owned by the app developer but rather his or her organization. For example, for us the apps should belong to Cemosis and we should be able to allow a team of developers to update the offering

/cc @vincentchabannes @gdolle @Trophime @emepetres @victorsndvg

**Comment by victorsndvg** [comment] 2018-06-08 10:14
I agree, for ECMI we should think in create a unique organization to contain all demos. This solution let anyone of the organization accept sellings. I'm right? do you agree?

**Comment by emepetres** [comment] 2018-06-08 11:09
This is a duplicate of #67 . It is not planned to do for ECMI because it is not so trivial to implement. I cannot promise to have it available for EMCI, but I'm going to put it at the top of the backlog and I'll see if I can finally have some time to implement it before the conference.

**Closed by emepetres** 2018-06-08 11:09 UTC
Labels: duplicate
