### ISSUE TITLE
New cluster add deployment step bug

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/MSOPortal#60] opened 2018-05-23 15:50 UTC
I added our cluster. But on last version I get this error during deployment when sending the job script to the cluster. (Note I have no file even when I skip the clean up).
Maybe it's due to the ssh command ?
```
2018-05-23T15:14:21.135Z Starting node job_toolboxes_p9t0e4 (job_toolboxes)
2018-05-23T15:14:21.219Z Sending task 'hpc_plugin.tasks.bootstrap_job' job_toolboxes_p9t0e4 (job_toolboxes)
2018-05-23T15:14:21.298Z Task started 'hpc_plugin.tasks.bootstrap_job' job_toolboxes_p9t0e4 (job_toolboxes)
2018-05-23T15:14:24.015Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment job_toolboxes_p9t0e4 (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
    Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
```

**Comment by emepetres** [comment] 2018-06-08 11:04
Duplicate of #75

**Closed by emepetres** 2018-06-08 11:04 UTC
Labels: duplicate
