### ISSUE TITLE
First UNISTRA users feedback!

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/MSOPortal#101] opened 2018-06-08 15:45 UTC
@victorsndvg (@prudhomm @vincentchabannes  @emepetres)

We got our first users (~20 people) feedbacks.
Currently, it is not possible to test Feel++ apps, most of our users get stuck with the singularity image download steps. sregistry server does not support the charge, we **must** change the way we proceed with Feel++ apps, this is a _top priority_ before ECMI.

@victorsndvg I propose to go back to how we proceed a long time ago. Can you provide a shared folder on ft2 so that we just copy singularity images in this shared location. Then use a copy/paste bootstrap instead of download ?

**Comment by prudhomm** [comment] 2018-06-08 18:00
Honestly that is the best way to go with the testing the next two weeks. Downloading images all the time is not an option especially if it is broken like now.

**Comment by prudhomm** [comment] 2018-06-11 09:27
@victorsndvg @emepetres without this we have to withdraw our participation to ECMI sprint.

**Comment by emepetres** [comment] 2018-06-11 11:19
I think this is a duplicate of https://github.com/MSO4SC/cloudify-hpc-plugin/issues/65 , let's keep the discussion on the other one.

**Closed by emepetres** 2018-06-11 11:19 UTC
Labels: duplicate
